language: python
python:
  - "2.7"
before_script:
  - flake8 mrburns smithers
script: coverage run manage.py test && cd smithers && NOSE_WITH_COV=1 nosetests
install:
  - bin/peep.py install -r requirements/qa.txt
after_success:
  # Report coverage results to coveralls.io
  - pip install coveralls
  - coveralls
notifications:
  irc:
    channels:
      - "irc.mozilla.org#glow"
    on_success: change
    on_failure: always
    use_notice: true
