language: python
python:
  - "2.7"
before_script:
  - flake8 mrburns smithers
script: cd smithers && coverage run nosetests
install:
  - bin/peep.py install -r requirements/mrburns.txt -r requirements/smithers.txt
after_success:
  # Report coverage results to coveralls.io
  - pip install coveralls
  - coveralls
notifications:
  irc:
    channels:
      - "irc.mozilla.org#glow"
    on_success: change
    on_failure: always
    use_notice: true
